CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(16) UNIQUE NOT NULL,
    passwd_hash VARCHAR(100) NOT NULL
    CONSTRAINT users_pk PRIMARY KEY (username)
);

CREATE TABLE IF NOT EXISTS chats (
	chat_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	friendname VARCHAR(16) NOT NULL,
	ownername VARCHAR(16) NOT NULL,
	last_message_id int NULL,
	"read-status" boolean NULL,
	CONSTRAINT chats_pk PRIMARY KEY (chat_id)
);
