version: '3.5'

services:
  chatia_db:
    image: postgres:14.3-alpine
    container_name: chatia_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
